In [3]:
import numpy as np
import matplotlib.pyplot as plt
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [9]:
a[...,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
out = a[...,:].cumsum(-1)[...,:]
for i in range(2,a.ndim+1):
    np.cumsum(out, axis=-i, out=out)


In [13]:
out

array([[ 1,  3,  6],
       [ 5, 12, 21],
       [12, 27, 45]])

In [6]:
a[...,:].cumsum(-1)[...,:]

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]])

In [14]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])